
CREATE TABLE IF NOT EXISTS plugin_videos_categories (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_user INTEGER NOT NULL,
	name VARCHAR(100) NOT NULL,
	FOREIGN KEY(id_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS plugin_videos_videos (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_category INTEGER NOT NULL,
	name VARCHAR(100) NOT NULL,
	url VARCHAR(150) NOT NULL,
	urlembeded VARCHAR(150) NOT NULL,
	FOREIGN KEY(id_category) REFERENCES plugin_videos_categories(id) ON DELETE CASCADE ON UPDATE CASCADE
);
